name: Build and Deploy to Render (.NET)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./EmprestimoLivros.csproj

    - name: Build project
      run: dotnet build ./EmprestimoLivros.csproj --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish ./EmprestimoLivros.csproj -c Release -o ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Render
      uses: render-examples/deploy-action@v1
      with:
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}
        apiKey: ${{ secrets.RENDER_API_KEY }}
