name: Build and Test (.NET)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./EmprestimoLivros/EmprestimoLivros.csproj

    - name: Build
      run: dotnet build ./EmprestimoLivros/EmprestimoLivros.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./EmprestimoLivros/EmprestimoLivros.csproj -c Release -o ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./publish
